#!/usr/bin/perl

$NrNodes = $ARGV[0];

for ($i=0; $i<$NrNodes; $i++) {
    if ($i==0) {
        $x = 0;
    } else {
        $x = int(rand(1000));
    }
    print "$x";
    for ($j=1; $j<$NrNodes; $j++) {
        if ($i!=$j) {
            $x = int(rand(1000));
        } else {
            $x = 0;
        }
        print " $x";
    }
    print "\n";
}
